name: Daily

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#42_9_*_*_*
    - cron: "42 9 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v4
        with:
          path: "tmp"
          key: "tmp"

      - name: Get Tags
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/get-tags.sh

      - name: Get Files
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/get-files.sh

      - name: Extract Versions
        shell: bash
        run: ./scripts/extract-versions.sh

      - name: Merge Data
        shell: bash
        run: ./scripts/merge-data.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          assignees: "erri120"
          reviewers: "erri120"

